version: 2
updates:
  - package-ecosystem: uv
    directory: /
    schedule:
      interval: daily
    groups:
      fastmcp:
        patterns:
          - fastmcp
      supabase:
        patterns:
          - supabase
      dev-tools:
        patterns:
          - pytest*
          - pylint

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
