version: 2
updates:
  - package-ecosystem: uv
    directory: /
    assignees:
      - thatleda
    schedule:
      interval: daily
      
  - package-ecosystem: github-actions
    directory: .github/workflows
    assignees:
      - thatleda
    schedule:
      interval: daily
